# site info
baseurl: ""
description: >
  Fully qualified and professional tree surgeon based
  in Kenilworth, UK. Covering surrounding areas.
email: a.roddy123@yahoo.co.uk
google_measurement: G-V66YXY9NLC
remote_theme: pages-themes/hacker
repository: paddyroddy/adr-tree-tree-website
title: A.D.R Tree Surgery
url: https://www.adrtreesurgery.co.uk

# social media
facebook_username: ADRTreeSurgery
phone_number: "+44-7397-989-051"

# image gallery
img_per_col: 2
