---
name: deploy

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  build-and-deploy:
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/github-pages/jekyll@7deb4fa12e279c6badc8c990391364ca10c817f1 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ruby-version: "3.2"
